version: 2
project_name: Gobin

builds:
  - id: hexinsuyangsummary
    dir: ./cmd/hexinsuyangsummary
    binary: hexinsuyangsummary
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

  - id: makemf
    dir: ./cmd/makemf
    binary: makemf
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

  - id: ollamaplist
    dir: ./cmd/ollamaplist
    binary: ollamaplist
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

  - id: reportgen
    dir: ./cmd/reportgen
    binary: reportgen
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

  - id: shicaojiaoan
    dir: ./cmd/shicaojiaoan
    binary: shicaojiaoan
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - id: hexinsuyangsummary
    builds: [hexinsuyangsummary]
    format: tar.gz
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

  - id: makemf
    builds: [makemf]
    format: tar.gz
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

  - id: ollamaplist
    builds: [ollamaplist]
    format: tar.gz
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

  - id: reportgen
    builds: [reportgen]
    format: tar.gz
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

  - id: shicaojiaoan
    builds: [shicaojiaoan]
    format: tar.gz
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

release:
  github:
    owner: Mrered
    name: Gobin
