version: 2
project_name: Gobin

builds:
  - id: ollamaplist
    dir: ./cmd/ollamaplist
    binary: ollamaplist
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

release:
  github:
    owner: Mrered
    name: Gobin