version: 2
project_name: Gobin

builds:
  - id: makemf
    dir: ./cmd/makemf
    binary: makemf
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

  - id: ollamaplist
    dir: ./cmd/ollamaplist
    binary: ollamaplist
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - id: makemf
    builds: [makemf]
    format: tar.gz
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

  - id: ollamaplist
    builds: [ollamaplist]
    format: tar.gz
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

release:
  github:
    owner: Mrered
    name: Gobin
